FROM postgres:18-bookworm

USER root

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
	postgis \
	postgresql-18-postgis-3 \
	&& rm -rf /var/lib/apt/lists/*

RUN printf '%s\n' \
	'CREATE EXTENSION IF NOT EXISTS postgis;' \
	'CREATE EXTENSION IF NOT EXISTS postgis_topology;' \
	> /docker-entrypoint-initdb.d/01-postgis.sql

USER postgres
