@startuml models
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 50
skinparam ranksep 60
left to right direction

class User {
  +id: Integer
  +username: String
  +email: String
  +first_name: String
  +last_name: String
  +hashed_password: String
}

class Trip {
  +id: Integer
  +user_id: Integer
  +destination: Location
  +start_date: String
  +end_date: String
  +status: TripStatus
}

enum TripStatus {
  PLANNED
  COMPLETED
  CANCELLED
}

class Location {
  +id: Integer
  +name: String
  +latitude: String
  +longitude: String
  +description: String
}

class Tag {
  +id: Integer
  +name: String
  +description: String
  +color: String
}

Location "0..*" -- "0..*" Tag : location_tags
User "1" --> "0..*" Trip : user_id
Trip "0..*" --> "1" Location : destination
Trip --> TripStatus : status
@enduml
